GET http://localhost:3000/api/stock

###

GET http://localhost:3000/api/stock/5e0e33c0ccfbec2ae6356bb6

###

POST http://localhost:3000/api/stock
Content-Type: application/json

{
    "name": "Schoolbag",
    "quantity": 10,
    "price": 2.90,
    "stockTo": "shop"
}